# Resolve react_native_pods.rb with node to allow for hoisting
begin
  require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )', __dir__]).strip
rescue => e
  raise "Failed to resolve react_native_pods.rb: #{e.message}"
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

## Firebolt version 
firebolt_version = ENV['FIREBOLT_VERSION'] || '1.0.16-alpha'
# Flipper configuration based on environment variable
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Check if we should use frameworks
linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'fireboltNew' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'fireboltNewTests' do
    inherit! :complete
    # Add any necessary testing pods here
    # e.g., pod 'SomeTestingLibrary'
  end

  post_install do |installer|
    # Perform post-installation steps for React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Add any additional pod adjustments here if needed
    installer.pods_project.targets.each do |target|
      # Example: Remove unused architectures
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
